version: '3'

services:
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./nginx_logs:/var/log/doctrine
    ports:
      - "8080:80"

  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - ./:/var/www/doctrine
    depends_on:
      - database

  database:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
